Blog/urls.py
# from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    path('about/', views.about),
    path('', views.homepage),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),


]

articles/urls.py
from django.urls import path, re_path
# from django.urls import re_path

from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name="list"),
    path('create/', views.article_create, name="create"),
    re_path(r'^(?P<slug>[\w-]+)/$', views.article_detail, name="detail"),

]

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)


    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...' 

articles/forms.py
from django import forms
from .import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'image'] 

Blog/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    # return HttpResponse('homepage')
    return render(request, 'homepage.html')

def about(request):
    # return HttpResponse('about')
    return render(request, 'about.html')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


# Create your views here.

def signup_view(request):

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            #if the user exist log him in
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #Log in the user
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
        form = AuthenticationForm
    return render(request, 'accounts/login.html', {'form': form})
    
def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from . import forms
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

# Create your views here.
def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/article_list.html', {'articles': articles})

def article_detail(request, slug):
    # return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article': article})

@login_required(login_url="/accounts/login")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST)
        if form.is_valid():
            #save in the db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', {'form': form})

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h2>Sign In</h2>

    {{ data }}
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next}}" id="">
        {% endif %}
        <input type="submit" value="Login">

    </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h2>Sign up</h2>

    {{ data }}
    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Register">

    </form>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}


{% block content %}
    <div class="create-article">
        <h2>Create an awesome new article</h2>
        <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create article">
        </form>
    </div>

{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}


{% block content %}
    <div class="article_detail">
        <div class="article">
            <img src="{{ article.image.url }}" alt="">
            <h2>{{ article.title }}</h2>
            <p>{{ article.body }}</p>
            <p>{{ article.date }}</p>

        </div>
    </div>

{% endblock%}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
	<h1>Article list</h1>
	<div class="articles">
		{% for article in articles %}
		<div class="article">
			<h2><a href="{% url 'articles:detail' article.slug %}"> {{ article.title }}</a></h2>
			<p>{{ article.snippet}}</p>
			<p>{{ article.date}}</p>
		</div>
		{% endfor %}
	</div>
{% endblock %}

templates/about.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>About page</title>
  </head>
  <body>
    <h1>About page</h1>
    <p>Welcome to the about page</p>
    <p>We like Django</p>
  </body>
</html>

templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
	<meta charset="utf-8">
	<title>Article list</title>
	<link rel="stylesheet" href="{% static 'style.css' %}">

</head>
<body>

    <div class="wrapper">
        <h1><a href="{% url 'articles:list' %}"> <img src="{% static 'logo.png'%}" alt=""> </a></h1>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="POST" >
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                    <li><a href="{% url 'articles:create' %}" class="highlight">New Article</a></li>

                {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
                {% endif %}
            </ul>
        </nav>

        <br>
        {% block content%}

        {% endblock%}
    </div>



</body>
</html>

<style>

</style>

templates/homepage.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>home page</title>
  </head>
  <body>
    <h1>Home page</h1>
    <p>Welcome to the home page</p>
  </body>
</html>